import {createSearch} from './search.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pageNames=['倉庫1階 A・B・C','倉庫2階 D','本管倉庫 E・F','KP倉庫 G','事務所 I・J','全体配置 H・C22'];
let data,search,page=6,area='',shelf='',tab='map',limit=50,zoom=1,matches=[],timer,request=0;
const areas='ABCDEFGHIJ'.split('');
function setTab(t){tab=t;for(const x of ['map','results','quality'])$(x+'-view').hidden=x!==t;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));}
function location(id){return data.locations.find(x=>x.id===id);}
function place(id){const l=location(id);return l?.boxes.length?[...new Set(l.boxes.map(b=>pageNames[b.page-1].split(' ')[0]))].join(' / '):id[0]==='J'?'事務所・個別位置未確定':'図面位置未確定';}
function filtered(){return matches.filter(x=>(!area||x.product.locationId[0]===area)&&(!shelf||x.product.locationId===shelf));}
function productCard({product:p,fuzzy}){return `<article class="product"><div class="product-top"><span class="code">${esc(p.code)}</span><span class="location">${esc(p.locationId)}</span></div><h3>${esc(p.name)}</h3><div class="meta">規格：${esc(p.spec.trim()||'未登録')}${p.order?'　／　棚順：'+esc(p.order):''}</div>${fuzzy?'<span class="fuzzy">入力に近い候補</span>':''}<div class="product-bottom"><small>${esc(place(p.locationId))}<br>元データ ${p.sourceRow}行</small><button data-locate="${esc(p.locationId)}">${location(p.locationId)?.boxes.length?'場所を見る':'棚の商品を見る'}</button></div></article>`;}
function renderResults(){const r=filtered();$('result-count').textContent=r.length.toLocaleString()+'件';$('search-status').textContent=r.length.toLocaleString()+'件';$('results-title').textContent=$('query').value?'検索結果':'商品一覧';$('filter-summary').innerHTML=area||shelf?`<button id="remove-result-filter">${esc(shelf||area)} の絞り込みを解除 ×</button>`:'';$('results').innerHTML=r.slice(0,limit).map(productCard).join('')||'<div class="empty">該当する商品がありません。<p>キーワードを短くするか、エリア・棚の絞り込みを解除してください。</p></div>';$('more').hidden=r.length<=limit;const mb=filtered();$('map-products').innerHTML=(shelf||area)?mb.slice(0,12).map(productCard).join('')+(mb.length>12?'<button id="show-all" class="more">この場所の商品をすべて見る（'+mb.length+'件）</button>':''):'';$('selection').innerHTML=shelf?`<div class="selection-label">${esc(shelf)}　${mb.length}件</div>${location(shelf)?.boxes.length?'':'<p class="warning">この棚の個別位置は図面で確定できません。棚番と商品はExcelの登録値です。</p>'}`:area?`<div class="selection-label">${area}エリア　${mb.length}件</div>`:'';}
function renderMap(){ $('pages').innerHTML=pageNames.map((n,i)=>`<button data-page="${i+1}" class="${page===i+1?'active':''}">${i+1}. ${n}</button>`).join('');$('areas').innerHTML=areas.map(a=>`<button data-area="${a}" class="${area===a?'active':''}">${a}<small>${data.products.filter(p=>p.locationId[0]===a).length}件</small></button>`).join('');$('layout').src=`layout-${page}.png`;$('layout').alt=pageNames[page-1]+'の棚配置図';$('drawing-caption').textContent=pageNames[page-1];$('drawing').style.width=zoom*100+'%';let spots=[];for(const l of data.locations)for(const b of l.boxes.filter(b=>b.page===page))spots.push(`<button class="hotspot ${shelf===l.id?'selected':''}" data-shelf="${l.id}" style="left:${b.x}%;top:${b.y}%;width:${b.w}%;height:${b.h}%" aria-label="${l.id}棚 ${l.count}件" aria-pressed="${shelf===l.id}"><span>${l.id}</span></button>`);
if(page===6){const regions=[['I',42,28,21,12],['A',42,42,10,8],['B',42,51,10,8],['C',42,60,10,8],['D',53,42,10,25],['E',14,76,14,13],['F',30,76,18,13],['G',51,72,15,14]];for(const [a,x,y,w,h] of regions)spots.push(`<button class="hotspot overview-hotspot" data-area="${a}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%" aria-label="${a}エリアの商品"><span>${a}</span></button>`);}
$('hotspots').innerHTML=spots.join('');let locs=data.locations.filter(l=>area?l.area===area:l.boxes.some(b=>b.page===page)||page===5&&l.area==='J');$('shelf-title').textContent=area?area+'エリアの棚':'この図面の棚';$('shelves').innerHTML=locs.map(l=>`<button data-shelf="${l.id}" class="${l.id===shelf?'active':''}">${l.id}<small>${l.count}件${l.boxes.length?'':' ※'}</small></button>`).join('');renderResults();}
function selectShelf(id,scroll=false){clearTimeout(timer);request++;$('query').value='';matches=search('');shelf=id;area=id[0];const l=location(id);if(l.boxes.length)page=l.boxes[0].page;else if(id[0]==='J')page=5;else page=id[0]==='F'?3:1;zoom=1;limit=50;setTab('map');renderMap();if(scroll){$('map-view').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.querySelector('.hotspot.selected')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'}),150);}}
function selectArea(a){clearTimeout(timer);request++;$('query').value='';matches=search('');area=a;shelf='';page={A:1,B:1,C:1,D:2,E:3,F:3,G:4,H:6,I:5,J:5}[a];zoom=1;limit=50;setTab('map');renderMap();}
function renderQuality(){const s=data.summary;$('quality-summary').innerHTML=`<div class="stats"><div class="stat">商品レコード<strong>${s.rows.toLocaleString()}</strong></div><div class="stat">商品コード重複<strong>${s.duplicateCodes}</strong></div><div class="stat">棚順の空欄<strong>${s.missingOrder}</strong></div><div class="stat">図面位置未確定<strong>${s.unmappedRows}</strong></div></div><div class="notes"><h2>解析結果</h2><p>「在庫コード」1シート、5列。見出し：棚段 / 棚順 / 商品ｺｰﾄﾞ / 商品名 / 規格。商品コード・商品名・棚段に欠損なし。規格は空白文字のみが34件。完全一致の重複行なし。</p><p>${esc(s.normalizationNote)}</p><p>${esc(s.manufacturerNote)}</p><p>${esc(s.layoutNote)}</p><p>未確定棚：${s.unmappedLocations.join('、')}。未確定の商品も検索対象です。別名は検索辞書で補完しています。数量は未登録（0とは扱いません）。</p></div>`;const issues=data.issues.filter(i=>!$('issue-type').value||i.type===$('issue-type').value);$('issue-count').textContent=issues.length+'件の確認項目';$('issues').innerHTML=issues.map(i=>`<div class="issue"><strong>${esc(i.type)}</strong>　${esc(i.location)}<br>${esc(i.code)}　<small>Excel ${i.row}行</small><br>${esc(i.detail)}</div>`).join('')||'<p>該当する確認項目はありません。</p>';}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!data)return;if(b.dataset.tab)setTab(b.dataset.tab);if(b.dataset.page){page=Number(b.dataset.page);area='';shelf='';zoom=1;renderMap();}if(b.dataset.area)selectArea(b.dataset.area);if(b.dataset.shelf)selectShelf(b.dataset.shelf);if(b.dataset.locate)selectShelf(b.dataset.locate,true);if(['reset-filter','remove-result-filter'].includes(b.id)){area='';shelf='';renderMap();}if(b.id==='show-all')setTab('results');});
function doSearch(){const ticket=++request;$('search-status').textContent='検索中…';clearTimeout(timer);timer=setTimeout(()=>{const started=performance.now();matches=search($('query').value);if(ticket!==request)return;limit=50;renderResults();$('search-status').title=Math.round(performance.now()-started)+'ms';},180);}
$('query').addEventListener('input',()=>{area='';shelf='';setTab('results');doSearch();});$('clear').onclick=()=>{$('query').value='';doSearch();$('query').focus();};$('more').onclick=()=>{limit+=50;renderResults();};$('zoom-in').onclick=()=>{zoom=Math.min(2.5,zoom+.25);$('drawing').style.width=zoom*100+'%';};$('zoom-out').onclick=()=>{zoom=Math.max(1,zoom-.25);$('drawing').style.width=zoom*100+'%';};$('issue-type').onchange=renderQuality;
$('clear-cache').onclick=async()=>{for(const k of await caches.keys())if(k.startsWith('tanasagashi-'))await caches.delete(k);for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();$('connection').textContent='端末保存を削除済み';};
try{const response=await fetch('data.json');if(!response.ok)throw Error('HTTP '+response.status);data=await response.json();search=createSearch(data.products);matches=search('');$('loading').hidden=true;$('total').textContent=data.products.length.toLocaleString()+'件 / '+data.locations.filter(l=>l.count).length+'棚';renderMap();renderQuality();setTab('map');$('connection').textContent=navigator.onLine?'商品データ読込済み':'オフライン';if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{$('connection').textContent='オンライン利用';});navigator.serviceWorker.addEventListener('message',e=>{if(e.data==='cached')$('connection').textContent='端末に保存済み';});}window.addEventListener('offline',()=>{$('connection').textContent='オフライン';});window.addEventListener('online',()=>{$('connection').textContent='オンライン';});}catch(error){$('loading').textContent='データを読み込めませんでした。接続を確認して再読み込みしてください。';console.error(error);}


