import {manufacturerOf,manufacturerIndex,matchManufacturer} from './manufacturers.mjs';
import {createSearch} from './search.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pageNames=['倉庫1階 A・B・C','倉庫2階 D','本管倉庫 E・F','KP倉庫 G','事務所 I・J','全体配置 H・C22'];
let manufacturer='',makers=[];
let data,search,page=6,area='',shelf='',tab='map',limit=50,zoom=1,matches=[],timer,request=0;
const areas='ABCDEFGHIJ'.split('');
function setTab(t){tab=t;for(const x of ['map','manufacturers','results','quality'])$(x+'-view').hidden=x!==t;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));}
function location(id){return data.locations.find(x=>x.id===id);}
function place(id){const l=location(id);return l?.boxes.length?[...new Set(l.boxes.map(b=>pageNames[b.page-1].split(' ')[0]))].join(' / '):id[0]==='J'?'事務所・個別位置未確定':'図面位置未確定';}
function filtered(){return matches.filter(x=>(!area||x.product.locationId[0]===area)&&(!shelf||x.product.locationId===shelf)&&(!manufacturer||manufacturerOf(x.product)===manufacturer));}
function productCard({product:p,fuzzy}){return `<article class="product"><div class="product-top"><button class="code code-button" data-detail="${esc(p.code)}" aria-label="${esc(p.code)}の商品詳細を開く">${esc(p.code)}</button><span class="location">${esc(p.locationId)}</span></div><h3><button class="product-name-button" data-detail="${esc(p.code)}">${esc(p.name)}</button></h3><div class="meta">規格：${esc(p.spec.trim()||'未登録')}${p.order?'　／　棚順：'+esc(p.order):''}</div>${fuzzy?'<span class="fuzzy">入力に近い候補</span>':''}<div class="product-bottom"><small>${esc(place(p.locationId))}<br>元データ ${p.sourceRow}行</small><button data-locate="${esc(p.locationId)}">${location(p.locationId)?.boxes.length?'場所を見る':'棚の商品を見る'}</button></div></article>`;}
function findProduct(code){return data.products.find(p=>String(p.code)===String(code));}
function searchText(p){return [p.code,p.name,p.spec].filter(Boolean).join(' ').trim();}
const imageKey=code=>'tanasagashi-image:'+code;
function savedImage(code){try{return localStorage.getItem(imageKey(code))||''}catch{return ''}}
function resizeImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.78));};img.src=r.result;};r.readAsDataURL(file);});}
async function saveProductImage(code,file){if(!file)return;try{const url=await resizeImage(file);localStorage.setItem(imageKey(code),url);showDetail(code);}catch(e){alert('画像を保存できませんでした。別の写真で試してください。');console.error(e);}}
function removeProductImage(code){try{localStorage.removeItem(imageKey(code));showDetail(code);}catch{}}
function showDetail(code){const p=findProduct(code);if(!p)return;const q=encodeURIComponent(searchText(p));const image=savedImage(p.code)||p.image||p.imageUrl||'';const mapped=location(p.locationId)?.boxes.length;let d=$('product-detail');if(!d){d=document.createElement('dialog');d.id='product-detail';d.className='product-detail';document.body.appendChild(d);}d.innerHTML=`<div class="detail-head"><div><small>商品詳細</small><h2>${esc(p.name)}</h2></div><button class="detail-close" data-close-detail aria-label="閉じる">×</button></div><div class="detail-image">${image?`<img src="${esc(image)}" alt="${esc(p.name)}の商品画像" loading="lazy">`:'<div class="image-empty"><span>📦</span><strong>画像未登録</strong><small>必要な時だけネットで画像を確認できます</small></div>'}</div><div class="image-tools"><label class="image-add">📷 ${image?'画像を変更':'写真を追加'}<input type="file" accept="image/*" data-image-upload="${esc(p.code)}"></label>${savedImage(p.code)?`<button class="image-remove" data-image-remove="${esc(p.code)}">登録画像を削除</button>`:''}</div><dl class="detail-info"><div><dt>品番</dt><dd>${esc(p.code)}</dd></div><div><dt>商品名</dt><dd>${esc(p.name)}</dd></div><div><dt>規格</dt><dd>${esc(p.spec?.trim()||'未登録')}</dd></div><div><dt>棚位置</dt><dd><strong class="detail-location">${esc(p.locationId)}</strong>　${esc(place(p.locationId))}</dd></div></dl><div class="detail-actions"><button class="detail-action primary" data-web-search="${esc(searchText(p))}" data-search-kind="image">🔎 この商品の画像を検索</button><button class="detail-action" data-web-search="${esc(searchText(p))}" data-search-kind="web">🏭 メーカー・商品情報を検索</button><button data-locate="${esc(p.locationId)}">📍 ${mapped?'棚位置を見る':'棚の商品を見る'}</button></div><p class="detail-note">画像は保存・転載せず、検索結果をその都度確認する方式です。アプリの追加利用料はかかりません。</p>`;d.showModal();}
function renderResults(){const r=filtered();$('result-count').textContent=r.length.toLocaleString()+'件';$('search-status').textContent=r.length.toLocaleString()+'件';$('results-title').textContent=manufacturer?manufacturer+'の商品':$('query').value?'検索結果':'商品一覧';$('filter-summary').innerHTML=manufacturer?`<button id="remove-manufacturer-filter">${esc(manufacturer)} の絞り込みを解除 ×</button><button data-tab="manufacturers">メーカーを選び直す</button>`:area||shelf?`<button id="remove-result-filter">${esc(shelf||area)} の絞り込みを解除 ×</button>`:'';$('results').innerHTML=r.slice(0,limit).map(productCard).join('')||'<div class="empty">該当する商品がありません。<p>キーワードを短くするか、エリア・棚の絞り込みを解除してください。</p></div>';$('more').hidden=r.length<=limit;const mb=filtered();$('map-products').innerHTML=(shelf||area)?mb.slice(0,12).map(productCard).join('')+(mb.length>12?'<button id="show-all" class="more">この場所の商品をすべて見る（'+mb.length+'件）</button>':''):'';$('selection').innerHTML=shelf?`<div class="selection-label">${esc(shelf)}　${mb.length}件</div>${location(shelf)?.boxes.length?'':'<p class="warning">この棚の個別位置は図面で確定できません。棚番と商品はExcelの登録値です。</p>'}`:area?`<div class="selection-label">${area}エリア　${mb.length}件</div>`:'';}
function renderMap(){ $('pages').innerHTML=pageNames.map((n,i)=>`<button data-page="${i+1}" class="${page===i+1?'active':''}">${i+1}. ${n}</button>`).join('');$('areas').innerHTML=areas.map(a=>`<button data-area="${a}" class="${area===a?'active':''}">${a}<small>${data.products.filter(p=>p.locationId[0]===a).length}件</small></button>`).join('');$('layout').src=`layout-${page}.svg`;$('layout').alt=pageNames[page-1]+'の棚配置図';$('drawing-caption').textContent=pageNames[page-1];$('drawing').style.width=zoom*100+'%';$('drawing').style.minWidth=zoom*100+'%';let spots=[];for(const l of data.locations)for(const b of l.boxes.filter(b=>b.page===page))spots.push(`<button class="hotspot ${shelf===l.id?'selected':''}" data-shelf="${l.id}" style="left:${b.x}%;top:${b.y}%;width:${b.w}%;height:${b.h}%" aria-label="${l.id}棚 ${l.count}件" aria-pressed="${shelf===l.id}"><span>${l.id}</span></button>`);
if(page===6){const regions=data.overviewRegions;for(const {area:a,x,y,w,h} of regions)spots.push(`<button class="hotspot overview-hotspot" data-area="${a}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%" aria-label="${a}エリアの商品"><span>${a}</span></button>`);}
$('hotspots').innerHTML=spots.join('');let locs=data.locations.filter(l=>area?l.area===area:l.boxes.some(b=>b.page===page)||page===5&&l.area==='J');$('shelf-title').textContent=area?area+'エリアの棚':'この図面の棚';$('shelves').innerHTML=locs.map(l=>`<button data-shelf="${l.id}" class="${l.id===shelf?'active':''}">${l.id}<small>${l.count}件${l.boxes.length?'':' ※'}</small></button>`).join('');renderResults();}
function selectShelf(id,scroll=false){manufacturer='';clearTimeout(timer);request++;$('query').value='';matches=search('');shelf=id;area=id[0];const l=location(id);if(l.boxes.length)page=l.boxes[0].page;else if(id[0]==='J')page=5;else page=id[0]==='F'?3:1;zoom=1;limit=50;setTab('map');renderMap();if(scroll){$('map-view').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.querySelector('.hotspot.selected')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'}),150);}}
function selectArea(a){manufacturer='';clearTimeout(timer);request++;$('query').value='';matches=search('');area=a;shelf='';page={A:1,B:1,C:1,D:2,E:3,F:3,G:4,H:6,I:5,J:5}[a];zoom=1;limit=50;setTab('map');renderMap();}
function renderQuality(){const s=data.summary;$('quality-summary').innerHTML=`<div class="stats"><div class="stat">商品レコード<strong>${s.rows.toLocaleString()}</strong></div><div class="stat">商品コード重複<strong>${s.duplicateCodes}</strong></div><div class="stat">棚順の空欄<strong>${s.missingOrder}</strong></div><div class="stat">図面位置未確定<strong>${s.unmappedRows}</strong></div></div><div class="notes"><h2>解析結果</h2><p>「在庫コード」1シート、5列。見出し：棚段 / 棚順 / 商品ｺｰﾄﾞ / 商品名 / 規格。商品コード・商品名・棚段に欠損なし。規格は空白文字のみが34件。完全一致の重複行なし。</p><p>${esc(s.normalizationNote)}</p><p>${esc(s.manufacturerNote)}</p><p>${esc(s.layoutNote)}</p><p>未確定棚：${s.unmappedLocations.join('、')}。未確定の商品も検索対象です。別名は検索辞書で補完しています。数量は未登録（0とは扱いません）。</p></div>`;const issues=data.issues.filter(i=>!$('issue-type').value||i.type===$('issue-type').value);$('issue-count').textContent=issues.length+'件の確認項目';$('issues').innerHTML=issues.map(i=>`<div class="issue"><strong>${esc(i.type)}</strong>　${esc(i.location)}<br>${esc(i.code)}　<small>Excel ${i.row}行</small><br>${esc(i.detail)}</div>`).join('')||'<p>該当する確認項目はありません。</p>';}
document.addEventListener('change',e=>{const input=e.target.closest('[data-image-upload]');if(input)saveProductImage(input.dataset.imageUpload,input.files?.[0]);});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!data)return;if(b.dataset.imageRemove){removeProductImage(b.dataset.imageRemove);return;}if(b.hasAttribute('data-close-detail')){$('product-detail')?.close();return;}if(b.dataset.webSearch){const term=encodeURIComponent(b.dataset.webSearch);const url=b.dataset.searchKind==='image'?'https://www.google.com/search?tbm=isch&q='+term:'https://www.google.com/search?q='+term;window.location.href=url;return;}if(b.dataset.detail){showDetail(b.dataset.detail);return;}if(b.dataset.tab)setTab(b.dataset.tab);if(b.dataset.manufacturer){selectManufacturer(b.dataset.manufacturer);return;}if(b.id==='remove-manufacturer-filter'){manufacturer='';renderResults();return;}if(b.dataset.page){manufacturer='';page=Number(b.dataset.page);area='';shelf='';zoom=1;renderMap();}if(b.dataset.area)selectArea(b.dataset.area);if(b.dataset.shelf)selectShelf(b.dataset.shelf);if(b.dataset.locate){$('product-detail')?.close();selectShelf(b.dataset.locate,true);}if(['reset-filter','remove-result-filter'].includes(b.id)){area='';shelf='';renderMap();}if(b.id==='show-all')setTab('results');});
function doSearch(){const ticket=++request;$('search-status').textContent='検索中…';clearTimeout(timer);timer=setTimeout(()=>{const started=performance.now();matches=search($('query').value);if(ticket!==request)return;limit=50;renderResults();$('search-status').title=Math.round(performance.now()-started)+'ms';},180);}
$('query').addEventListener('input',()=>{area='';shelf='';setTab('results');doSearch();});$('clear').onclick=()=>{$('query').value='';doSearch();$('query').focus();};$('more').onclick=()=>{limit+=50;renderResults();};
function applyZoom(delta){zoom=Math.max(1,Math.min(2.5,zoom+delta));const drawing=$('drawing'),scroller=$('drawing-scroll');drawing.style.width=(zoom*100)+'%';drawing.style.minWidth=(zoom*100)+'%';if(zoom===1)scroller.scrollTo({left:0,top:0,behavior:'smooth'});}
$('zoom-in').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();applyZoom(.25);});
$('zoom-out').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();applyZoom(-.25);});
$('issue-type').onchange=renderQuality;
$('clear-cache').onclick=async()=>{for(const k of await caches.keys())if(k.startsWith('tanasagashi-'))await caches.delete(k);for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();$('connection').textContent='端末保存を削除済み';};
try{const response=await fetch('data.json',{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);data=await response.json();search=createSearch(data.products);matches=search('');$('loading').hidden=true;$('total').textContent=data.products.length.toLocaleString()+'件 / '+data.locations.filter(l=>l.count).length+'棚';makers=manufacturerIndex(data.products);renderManufacturers();renderMap();renderQuality();setTab('map');$('connection').textContent=navigator.onLine?'商品データ読込済み':'オフライン';if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=14',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{$('connection').textContent='オンライン利用';});navigator.serviceWorker.addEventListener('message',e=>{if(e.data==='cached')$('connection').textContent='端末に保存済み';});}window.addEventListener('offline',()=>{$('connection').textContent='オフライン';});window.addEventListener('online',()=>{$('connection').textContent='オンライン';});}catch(error){$('loading').innerHTML='データを読み込めませんでした。<br><button id="retry-load">再読み込み</button>';$('connection').textContent='読込エラー';$('retry-load')?.addEventListener('click',()=>window.location.reload());console.error(error);}



function renderManufacturers(){
 const shown=makers.filter(m=>matchManufacturer(m,$('manufacturer-query').value));
 $('manufacturer-count').textContent=shown.length+'件';
 $('manufacturer-list').innerHTML=shown.map(m=>`<button data-manufacturer="${esc(m.name)}"><strong>${esc(m.name)}</strong><span>${m.count.toLocaleString()}商品 →</span></button>`).join('')||'<p class="empty">該当するメーカーがありません。名前の一部でも検索できます。</p>';
}
function selectManufacturer(name){
 clearTimeout(timer);request++;manufacturer=name;area='';shelf='';limit=50;$('query').value='';matches=search('');setTab('results');renderResults();$('results-view').scrollIntoView({behavior:'smooth',block:'start'});
}
$('manufacturer-query').addEventListener('input',renderManufacturers);