import {manufacturerOf,manufacturerIndex,matchManufacturer} from './manufacturers.mjs';
import {createSearch} from './search.mjs';
import {listPriceFor,formatListPrice} from './prices.mjs?v=23';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pageNames=['倉庫1階 A・B・C','倉庫2階 D','本管倉庫 E・F','KP倉庫 G','事務所 I・J','全体配置 H・C22'];
let manufacturer='',makers=[];let orders=[],activeOrderId='';
let data,search,page=6,area='',shelf='',tab='map',limit=50,zoom=1,matches=[],timer,request=0;
const areas='ABCDEFGHIJ'.split('');
function setTab(t){tab=t;for(const x of ['map','manufacturers','photos','results','quality','orders'])$(x+'-view').hidden=x!==t;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));}
function location(id){return data.locations.find(x=>x.id===id);}
function place(id){const l=location(id);return l?.boxes.length?[...new Set(l.boxes.map(b=>pageNames[b.page-1].split(' ')[0]))].join(' / '):id[0]==='J'?'事務所・個別位置未確定':'図面位置未確定';}
function filtered(){return matches.filter(x=>(!area||x.product.locationId[0]===area)&&(!shelf||x.product.locationId===shelf)&&(!manufacturer||manufacturerOf(x.product)===manufacturer));}
function productCard({product:p,fuzzy}){const price=listPriceFor(p);return `<article class="product"><div class="product-top"><button class="code code-button" data-detail="${esc(p.code)}" aria-label="${esc(p.code)}の商品詳細を開く">${esc(p.code)}</button><span class="location">${esc(p.locationId)}</span></div><h3><button class="product-name-button" data-detail="${esc(p.code)}">${esc(p.name)}</button></h3><div class="meta">規格：${esc(p.spec.trim()||'未登録')}${p.order?'　／　棚順：'+esc(p.order):''}</div>${price?`<div class="list-price"><span>税別定価</span><strong>${formatListPrice(price)}</strong><small>価格表確認</small></div>`:''}${fuzzy?'<span class="fuzzy">入力に近い候補</span>':''}<div class="product-bottom"><small>${esc(place(p.locationId))}<br>元データ ${p.sourceRow}行</small><button data-locate="${esc(p.locationId)}">${location(p.locationId)?.boxes.length?'場所を見る':'棚の商品を見る'}</button></div></article>`;}
function findProduct(code){return data.products.find(p=>String(p.code)===String(code));}
function searchText(p){return [p.code,p.name,p.spec].filter(Boolean).join(' ').trim();}
const ORDERS_KEY='tanasagashi-orders-v1',ACTIVE_ORDER_KEY='tanasagashi-active-order-v1';
function loadOrders(){try{orders=JSON.parse(localStorage.getItem(ORDERS_KEY)||'[]');if(!Array.isArray(orders))orders=[];activeOrderId=localStorage.getItem(ACTIVE_ORDER_KEY)||''}catch{orders=[];activeOrderId=''}}
function setActiveOrder(id=''){activeOrderId=String(id||'');try{if(activeOrderId)localStorage.setItem(ACTIVE_ORDER_KEY,activeOrderId);else localStorage.removeItem(ACTIVE_ORDER_KEY)}catch{}}
function persistOrders(){try{localStorage.setItem(ORDERS_KEY,JSON.stringify(orders));return true}catch(e){console.error('受注保存エラー',e);return false}}
function today(){return new Date().toLocaleDateString('sv-SE')}
function newOrder(code=''){const p=code?findProduct(code):null;return {id:'',date:today(),customer:'',site:'',delivery:'',staff:'',status:'未手配',note:'',items:[{code:p?.code||'',name:p?.name||'',spec:p?.spec||'',qty:1,unit:'個'}]}}
function orderRow(x={}){return '<div class="order-item" data-order-row><label>品番・商品検索<input class="order-code" value="'+esc(x.code||'')+'" placeholder="品番・商品名"></label><label>商品名<input class="order-name" value="'+esc(x.name||'')+'"></label><label>規格<input class="order-spec" value="'+esc(x.spec||'')+'"></label><label>数量<input class="order-qty" type="number" min="0" step="any" value="'+esc(x.qty||1)+'"></label><label>単位<input class="order-unit" value="'+esc(x.unit||'個')+'"></label><div class="order-suggest" hidden></div><button type="button" data-remove-order-row>×</button></div>'}
function renderOrders(){const e=$('orders-view');if(!e)return;const rank={'未手配':0,'手配済':1,'入荷済':2,'納品済':3},list=[...orders].sort((x,y)=>(rank[x.status]??9)-(rank[y.status]??9)||String(y.date).localeCompare(String(x.date)));e.innerHTML='<div class="orders-head"><div><h1>📋 受注</h1><p>この端末に保存。CSV出力・バックアップができます。</p></div><button id="orders-close">棚さがしへ戻る</button></div><div class="order-actions"><button id="new-order" class="primary-btn">＋ 新しい受注</button><button id="export-orders">📤 CSV出力</button><button id="backup-orders">💾 バックアップ</button><label class="import-order">📥 バックアップ読込<input id="import-orders" type="file" accept=".json,application/json"></label></div><div id="order-editor"></div><div class="order-list-head"><h2>受注一覧</h2><span>'+orders.length+'件</span></div><div class="order-list">'+(list.map(o=>'<article class="order-card"><div class="order-card-top"><strong>'+esc(o.customer||'得意先未入力')+'</strong><span class="order-status">'+esc(o.status||'未手配')+'</span></div><div class="order-sub">'+esc(o.date||'')+(o.site?' ／ '+esc(o.site):'')+'</div><ul>'+(o.items||[]).map(x=>'<li><b>'+esc(x.name||x.code)+'</b> '+esc(x.spec)+' <strong>×'+esc(x.qty)+' '+esc(x.unit||'個')+'</strong></li>').join('')+'</ul><div class="order-card-bottom"><small>'+(o.delivery?'希望納期 '+esc(o.delivery):'')+(o.staff?'　担当 '+esc(o.staff):'')+'</small><div><button data-order-edit="'+o.id+'">編集</button><button data-order-status="'+o.id+'">次へ</button><button data-order-delete="'+o.id+'" class="danger">削除</button></div></div></article>').join('')||'<div class="empty">まだ受注はありません。</div>')+'</div>'}
function editOrder(id='',code=''){const old=orders.find(o=>o.id===id),o=old?JSON.parse(JSON.stringify(old)):newOrder(code),e=$('order-editor');e.innerHTML='<form id="order-form" class="order-editor"><h2>'+(old?'受注を編集':'新しい受注')+'</h2><input type="hidden" name="id" value="'+esc(o.id)+'"><div class="order-fields"><label>受注日<input name="date" type="date" value="'+esc(o.date)+'" required></label><label>得意先名<input name="customer" value="'+esc(o.customer)+'"></label><label>現場名<input name="site" value="'+esc(o.site)+'"></label><label>希望納期<input name="delivery" type="date" value="'+esc(o.delivery)+'"></label><label>担当者<input name="staff" value="'+esc(o.staff)+'"></label><label>状態<select name="status">'+['未手配','手配済','入荷済','納品済'].map(s=>'<option '+(o.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select></label></div><h3>商品</h3><div id="order-items">'+o.items.map(orderRow).join('')+'</div><button type="button" id="add-order-item">＋ 商品を追加</button><label class="order-note">備考<textarea name="note" rows="3">'+esc(o.note)+'</textarea></label><div class="order-save"><button type="button" id="cancel-order">キャンセル</button><button class="primary-btn" type="button" id="save-order-now">受注を保存</button></div></form>';e.scrollIntoView({behavior:'smooth',block:'start'})}
function saveOrder(form){try{const f=new FormData(form),items=[...form.querySelectorAll('[data-order-row]')].map(r=>({code:r.querySelector('.order-code')?.value.trim()||'',name:r.querySelector('.order-name')?.value.trim()||'',spec:r.querySelector('.order-spec')?.value.trim()||'',qty:r.querySelector('.order-qty')?.value||1,unit:r.querySelector('.order-unit')?.value.trim()||'個'})).filter(x=>x.code||x.name),id=String(f.get('id')||Date.now().toString(36)),o={id,date:String(f.get('date')||today()),customer:String(f.get('customer')||'').trim(),site:String(f.get('site')||'').trim(),delivery:String(f.get('delivery')||''),staff:String(f.get('staff')||'').trim(),status:String(f.get('status')||'未手配'),note:String(f.get('note')||'').trim(),items};const n=orders.findIndex(x=>String(x.id)===id);if(n>=0)orders[n]=o;else orders.unshift(o);setActiveOrder(id);const stored=persistOrders();renderOrders();const list=document.querySelector('.order-list');if(list)list.insertAdjacentHTML('afterbegin','<div class="save-notice">✓ 受注を保存しました'+(stored?'':'（この端末の保存領域に書き込めないため、一時保存です）')+'</div>');}catch(e){console.error(e);alert('受注を保存できませんでした。入力内容を残したまま、もう一度お試しください。')}}
function csv(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function download(name,type,text){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportOrders(){const rows=[['受注日','得意先名','現場名','商品コード','商品名','規格','数量','単位','希望納期','担当者','状態','備考']];for(const o of orders)for(const x of o.items||[])rows.push([o.date,o.customer,o.site,x.code,x.name,x.spec,x.qty,x.unit,o.delivery,o.staff,o.status,o.note]);download('受注データ_'+today()+'.csv','text/csv;charset=utf-8','\ufeff'+rows.map(r=>r.map(csv).join(',')).join('\r\n'))}
function backupOrders(){download('棚さがし_受注バックアップ_'+today()+'.json','application/json',JSON.stringify({version:1,orders},null,2))}
function addProductToCurrentOrder(code){
 const p=findProduct(code);if(!p)return;
 let o=orders.find(x=>String(x.id)===String(activeOrderId));
 if(!o||o.status==='納品済'){o=newOrder();o.id=Date.now().toString(36);o.items=[];orders.unshift(o);setActiveOrder(o.id);}
 const item=o.items.find(x=>String(x.code)===String(p.code));
 if(item)item.qty=(Number(item.qty)||0)+1;else o.items.push({code:p.code,name:p.name,spec:p.spec||'',qty:1,unit:'個'});
 const stored=persistOrders();setTab('orders');renderOrders();
 const list=document.querySelector('.order-list'),message=item?'同じ商品の数量を増やしました':'商品を同じ受注に追加しました';
 if(list)list.insertAdjacentHTML('afterbegin','<div class="save-notice">✓ '+message+(stored?'':'（一時保存）')+'</div>');
 $('orders-view').scrollIntoView({behavior:'smooth',block:'start'});
}
function openOrders(){setTab('orders');renderOrders();$('orders-view').scrollIntoView({behavior:'smooth',block:'start'})}

const imageKey=code=>'tanasagashi-image:'+code;
function savedImage(code){try{return localStorage.getItem(imageKey(code))||''}catch{return ''}}
function resizeImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.78));};img.src=r.result;};r.readAsDataURL(file);});}
async function saveProductImage(code,file,reopen=true){if(!file)return;try{const url=await resizeImage(file);localStorage.setItem(imageKey(code),url);renderPhotos();if(reopen)showDetail(code);}catch(e){alert('画像を保存できませんでした。別の写真で試してください。');console.error(e);}}
function removeProductImage(code){try{localStorage.removeItem(imageKey(code));renderPhotos();showDetail(code);}catch{}}
function productImage(p){return savedImage(p.code)||p.image||p.imageUrl||'';}
function normalizeScan(s){return String(s||'').toUpperCase().normalize('NFKC').replace(/[‐‑‒–—―ー]/g,'-').replace(/[^A-Z0-9一-龠ぁ-んァ-ヶー]/g,'')}
function scanTokens(text){const raw=String(text||'').toUpperCase().normalize('NFKC'),parts=raw.split(/\s+|[,:;|()[\]{}<>「」『』【】]/).map(x=>x.trim()).filter(Boolean),tokens=new Set();for(const p of parts){const n=normalizeScan(p);if(n.length>=2)tokens.add(n);for(const m of p.matchAll(/[A-Z0-9][A-Z0-9._\/-]{2,}/g)){const x=normalizeScan(m[0]);if(x.length>=3)tokens.add(x)}}return [...tokens].sort((x,y)=>y.length-x.length).slice(0,60)}
function scanScore(p,tokens){const code=normalizeScan(p.code),name=normalizeScan(p.name),spec=normalizeScan(p.spec);let score=0,hits=[];for(const t of tokens){if(t.length<2)continue;let w=0;if(code&&(code.includes(t)||t.includes(code)))w=Math.max(w,t.length>=5?16:10);if(spec&&(spec.includes(t)||t.includes(spec)))w=Math.max(w,t.length>=4?10:6);if(name.includes(t))w=Math.max(w,t.length>=4?7:4);if(w){score+=w;hits.push(t)}}return {p,score,hits:[...new Set(hits)].slice(0,4)}}
function renderScanResults(text){const tokens=scanTokens(text),ranked=data.products.map(p=>scanScore(p,tokens)).filter(x=>x.score>0).sort((x,y)=>y.score-x.score).slice(0,8),box=$('scan-results');if(!ranked.length){box.innerHTML='<div class="scan-nohit"><strong>商品を特定できませんでした</strong><p>品番ラベルを近くから撮り直してください。光の反射やピンぼけを避けると読み取りやすくなります。</p></div>';return}const top=ranked[0].score,second=ranked[1]?.score||0,confident=top>=16&&top>=second+6;box.innerHTML='<div class="scan-read"><details><summary>読み取った文字を確認</summary><pre>'+esc(text.trim().slice(0,1200))+'</pre></details></div><div class="scan-result-title"><strong>'+(confident?'一致度の高い候補':'候補が複数あります')+'</strong><span>'+(confident?'商品名・品番を確認して棚へ':'商品を確認して選んでください')+'</span></div>'+ranked.map((x,n)=>{const p=x.p,l=location(p.locationId),mapped=!!l?.boxes.length;return '<article class="scan-candidate '+(n===0&&confident?'scan-best':'')+'"><div class="scan-rank">'+(n===0?'候補1':'候補'+(n+1))+'</div><div><strong>'+esc(p.name)+'</strong><div class="scan-meta">品番 '+esc(p.code)+' ／ 規格 '+esc(p.spec||'未登録')+'</div><div class="scan-hit">写真との一致: '+esc(x.hits.join('・'))+'</div></div><div class="scan-shelf"><small>片付ける棚</small><b>'+esc(p.locationId)+'</b><span>'+esc(place(p.locationId))+'</span></div><div class="scan-buttons"><button data-detail="'+esc(p.code)+'">商品詳細</button><button class="primary-btn" data-locate="'+esc(p.locationId)+'">'+(mapped?'📍 棚の場所を見る':'棚の商品を見る')+'</button></div></article>'}).join('')}
async function loadTesseract(){if(window.Tesseract)return window.Tesseract;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@7/dist/tesseract.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});return window.Tesseract}
async function scanShelfPhoto(file){if(!file)return;const status=$('scan-status'),preview=$('scan-preview'),results=$('scan-results');status.hidden=false;status.innerHTML='<strong>写真を読み取っています…</strong><span>初回はOCRデータの準備に少し時間がかかります。</span>';results.innerHTML='';const url=URL.createObjectURL(file);preview.innerHTML='<img src="'+url+'" alt="撮影した入荷商品">';try{const T=await loadTesseract();const worker=await T.createWorker(['jpn','eng'],1,{logger:m=>{if(m.status==='recognizing text')status.innerHTML='<strong>ラベルを解析中… '+Math.round((m.progress||0)*100)+'%</strong><span>メーカー名・品番・規格を探しています。</span>'}});const ret=await worker.recognize(file,{rotateAuto:true});await worker.terminate();const text=ret.data.text||'';status.innerHTML='<strong>読み取り完了</strong><span>商品マスター '+data.products.length.toLocaleString()+'件から候補を照合しました。</span>';renderScanResults(text)}catch(e){console.error(e);status.innerHTML='<strong>写真を読み取れませんでした</strong><span>インターネット接続を確認して、もう一度撮影してください。</span>';results.innerHTML='<div class="scan-nohit">OCRの初回読み込みには通信が必要です。</div>'}finally{setTimeout(()=>URL.revokeObjectURL(url),30000)}}
function renderPhotos(){if(!$('photo-count'))return;$('photo-count').textContent='ラベルOCR → 棚番照合'}
function showDetail(code){const p=findProduct(code);if(!p)return;const q=encodeURIComponent(searchText(p));const image=savedImage(p.code)||p.image||p.imageUrl||'',price=listPriceFor(p);const mapped=location(p.locationId)?.boxes.length;let d=$('product-detail');if(!d){d=document.createElement('dialog');d.id='product-detail';d.className='product-detail';document.body.appendChild(d);}const priceSource=price?(price.source?`<a href="${esc(price.source)}" target="_blank" rel="noopener">メーカー公式で確認</a>`:`<span class="price-source">${esc(price.sourceLabel||'価格表で確認')}</span>`):'';d.innerHTML=`<div class="detail-head"><div><small>商品詳細</small><h2>${esc(p.name)}</h2></div><button class="detail-close" data-close-detail aria-label="閉じる">×</button></div><div class="detail-image">${image?`<img src="${esc(image)}" alt="${esc(p.name)}の商品画像" loading="lazy">`:'<div class="image-empty"><span>📦</span><strong>画像未登録</strong><small>必要な時だけネットで画像を確認できます</small></div>'}</div><div class="image-tools"><label class="image-add">📷 ${image?'画像を変更':'写真を追加'}<input type="file" accept="image/*" data-image-upload="${esc(p.code)}"></label>${savedImage(p.code)?`<button class="image-remove" data-image-remove="${esc(p.code)}">登録画像を削除</button>`:''}</div><dl class="detail-info"><div><dt>品番</dt><dd>${esc(p.code)}</dd></div><div><dt>商品名</dt><dd>${esc(p.name)}</dd></div><div><dt>規格</dt><dd>${esc(p.spec?.trim()||'未登録')}</dd></div>${price?`<div class="detail-price-row"><dt>税別定価</dt><dd><strong>${formatListPrice(price)}</strong><br>${priceSource}<small>確認日 ${esc(price.checked)}</small></dd></div>`:''}<div><dt>棚位置</dt><dd><strong class="detail-location">${esc(p.locationId)}</strong>　${esc(place(p.locationId))}</dd></div></dl><div class="detail-actions"><button class="detail-action primary" data-web-search="${esc(searchText(p))}" data-search-kind="image">🔎 この商品の画像を検索</button><button class="detail-action" data-web-search="${esc(searchText(p))}" data-search-kind="web">🏭 メーカー・商品情報を検索</button><button data-locate="${esc(p.locationId)}">📍 ${mapped?'棚位置を見る':'棚の商品を見る'}</button><button class="detail-action order-add-detail" data-order-product="${esc(p.code)}">📋 この商品を受注に追加</button></div><p class="detail-note">定価は提供された2026年10月2日版の価格表に記載された税別定価です。</p>`;d.showModal();}
function renderResults(){const r=filtered();$('result-count').textContent=r.length.toLocaleString()+'件';$('search-status').textContent=r.length.toLocaleString()+'件';$('results-title').textContent=manufacturer?manufacturer+'の商品':$('query').value?'検索結果':'商品一覧';$('filter-summary').innerHTML=manufacturer?`<button id="remove-manufacturer-filter">${esc(manufacturer)} の絞り込みを解除 ×</button><button data-tab="manufacturers">メーカーを選び直す</button>`:area||shelf?`<button id="remove-result-filter">${esc(shelf||area)} の絞り込みを解除 ×</button>`:'';$('results').innerHTML=r.slice(0,limit).map(productCard).join('')||'<div class="empty">該当する商品がありません。<p>キーワードを短くするか、エリア・棚の絞り込みを解除してください。</p></div>';$('more').hidden=r.length<=limit;const mb=filtered();$('map-products').innerHTML=(shelf||area)?mb.slice(0,12).map(productCard).join('')+(mb.length>12?'<button id="show-all" class="more">この場所の商品をすべて見る（'+mb.length+'件）</button>':''):'';$('selection').innerHTML=shelf?`<div class="selection-label">${esc(shelf)}　${mb.length}件</div>${location(shelf)?.boxes.length?'':'<p class="warning">この棚の個別位置は図面で確定できません。棚番と商品はExcelの登録値です。</p>'}`:area?`<div class="selection-label">${area}エリア　${mb.length}件</div>`:'';}
function renderMap(){ $('pages').innerHTML=pageNames.map((n,i)=>`<button data-page="${i+1}" class="${page===i+1?'active':''}">${i+1}. ${n}</button>`).join('');$('areas').innerHTML=areas.map(a=>`<button data-area="${a}" class="${area===a?'active':''}">${a}<small>${data.products.filter(p=>p.locationId[0]===a).length}件</small></button>`).join('');$('layout').src=`layout-${page}.svg`;$('layout').alt=pageNames[page-1]+'の棚配置図';$('drawing-caption').textContent=pageNames[page-1];$('drawing').style.width=zoom*100+'%';$('drawing').style.minWidth=zoom*100+'%';let spots=[];for(const l of data.locations)for(const b of l.boxes.filter(b=>b.page===page))spots.push(`<button class="hotspot ${shelf===l.id?'selected':''}" data-shelf="${l.id}" style="left:${b.x}%;top:${b.y}%;width:${b.w}%;height:${b.h}%" aria-label="${l.id}棚 ${l.count}件" aria-pressed="${shelf===l.id}"><span>${l.id}</span></button>`);
if(page===6){const regions=data.overviewRegions;for(const {area:a,x,y,w,h} of regions)spots.push(`<button class="hotspot overview-hotspot" data-area="${a}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%" aria-label="${a}エリアの商品"><span>${a}</span></button>`);}
$('hotspots').innerHTML=spots.join('');let locs=data.locations.filter(l=>area?l.area===area:l.boxes.some(b=>b.page===page)||page===5&&l.area==='J');$('shelf-title').textContent=area?area+'エリアの棚':'この図面の棚';$('shelves').innerHTML=locs.map(l=>`<button data-shelf="${l.id}" class="${l.id===shelf?'active':''}">${l.id}<small>${l.count}件${l.boxes.length?'':' ※'}</small></button>`).join('');renderResults();}
function selectShelf(id,scroll=false){manufacturer='';clearTimeout(timer);request++;$('query').value='';matches=search('');shelf=id;area=id[0];const l=location(id);if(l.boxes.length)page=l.boxes[0].page;else if(id[0]==='J')page=5;else page=id[0]==='F'?3:1;zoom=1;limit=50;setTab('map');renderMap();if(scroll){$('map-view').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.querySelector('.hotspot.selected')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'}),150);}}
function selectArea(a){manufacturer='';clearTimeout(timer);request++;$('query').value='';matches=search('');area=a;shelf='';page={A:1,B:1,C:1,D:2,E:3,F:3,G:4,H:6,I:5,J:5}[a];zoom=1;limit=50;setTab('map');renderMap();}
function renderQuality(){const s=data.summary;$('quality-summary').innerHTML=`<div class="stats"><div class="stat">商品レコード<strong>${s.rows.toLocaleString()}</strong></div><div class="stat">商品コード重複<strong>${s.duplicateCodes}</strong></div><div class="stat">棚順の空欄<strong>${s.missingOrder}</strong></div><div class="stat">図面位置未確定<strong>${s.unmappedRows}</strong></div></div><div class="notes"><h2>解析結果</h2><p>「在庫コード」1シート、5列。見出し：棚段 / 棚順 / 商品ｺｰﾄﾞ / 商品名 / 規格。商品コード・商品名・棚段に欠損なし。規格は空白文字のみが34件。完全一致の重複行なし。</p><p>${esc(s.normalizationNote)}</p><p>${esc(s.manufacturerNote)}</p><p>${esc(s.layoutNote)}</p><p>未確定棚：${s.unmappedLocations.join('、')}。未確定の商品も検索対象です。別名は検索辞書で補完しています。数量は未登録（0とは扱いません）。</p></div>`;const issues=data.issues.filter(i=>!$('issue-type').value||i.type===$('issue-type').value);$('issue-count').textContent=issues.length+'件の確認項目';$('issues').innerHTML=issues.map(i=>`<div class="issue"><strong>${esc(i.type)}</strong>　${esc(i.location)}<br>${esc(i.code)}　<small>Excel ${i.row}行</small><br>${esc(i.detail)}</div>`).join('')||'<p>該当する確認項目はありません。</p>';}
document.addEventListener('change',e=>{const input=e.target.closest('[data-image-upload]');if(input)saveProductImage(input.dataset.imageUpload,input.files?.[0]);const photoInput=e.target.closest('[data-photo-upload]');if(photoInput)saveProductImage(photoInput.dataset.photoUpload,photoInput.files?.[0],false);if(e.target.id==='import-orders'){const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>{try{const j=JSON.parse(r.result);if(!Array.isArray(j.orders))throw Error();if(confirm(j.orders.length+'件の受注データを読み込みます。現在の受注は置き換わります。')){orders=j.orders;persistOrders();renderOrders()}}catch{alert('バックアップを読み込めませんでした')}};r.readAsText(f)}}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!data)return;if(b.dataset.orderProduct){$('product-detail')?.close();addProductToCurrentOrder(b.dataset.orderProduct);return;}if(b.dataset.orderEdit){setActiveOrder(b.dataset.orderEdit);editOrder(b.dataset.orderEdit);return;}if(b.dataset.orderStatus){const o=orders.find(x=>x.id===b.dataset.orderStatus),s=['未手配','手配済','入荷済','納品済'];if(o){o.status=s[Math.min(s.length-1,Math.max(0,s.indexOf(o.status)+1))];persistOrders();renderOrders()}return;}if(b.dataset.orderDelete){if(confirm('この受注を削除しますか？')){orders=orders.filter(x=>x.id!==b.dataset.orderDelete);if(activeOrderId===b.dataset.orderDelete)setActiveOrder('');persistOrders();renderOrders()}return;}if(b.hasAttribute('data-remove-order-row')){b.closest('[data-order-row]')?.remove();return;}if(b.id==='new-order'){setActiveOrder('');editOrder();return;}if(b.id==='save-order-now'){const form=b.closest('#order-form');if(form)saveOrder(form);return;}if(b.id==='add-order-item'){$('order-items').insertAdjacentHTML('beforeend',orderRow());return;}if(b.id==='cancel-order'){renderOrders();return;}if(b.id==='export-orders'){exportOrders();return;}if(b.id==='backup-orders'){backupOrders();return;}if(b.id==='orders-close'){setTab('map');return;}if(b.dataset.imageRemove){removeProductImage(b.dataset.imageRemove);return;}if(b.hasAttribute('data-close-detail')){$('product-detail')?.close();return;}if(b.dataset.webSearch){const term=encodeURIComponent(b.dataset.webSearch);const url=b.dataset.searchKind==='image'?'https://www.google.com/search?tbm=isch&q='+term:'https://www.google.com/search?q='+term;window.location.href=url;return;}if(b.dataset.detail){showDetail(b.dataset.detail);return;}if(b.dataset.tab){setTab(b.dataset.tab);if(b.dataset.tab==='photos')renderPhotos();}if(b.dataset.manufacturer){selectManufacturer(b.dataset.manufacturer);return;}if(b.id==='remove-manufacturer-filter'){manufacturer='';renderResults();return;}if(b.dataset.page){manufacturer='';page=Number(b.dataset.page);area='';shelf='';zoom=1;renderMap();}if(b.dataset.area)selectArea(b.dataset.area);if(b.dataset.shelf)selectShelf(b.dataset.shelf);if(b.dataset.locate){$('product-detail')?.close();selectShelf(b.dataset.locate,true);}if(['reset-filter','remove-result-filter'].includes(b.id)){area='';shelf='';renderMap();}if(b.id==='show-all')setTab('results');});
$('orders-open').addEventListener('click',()=>openOrders());
document.addEventListener('submit',e=>{if(e.target.id==='order-form'){e.preventDefault();saveOrder(e.target)}});
document.addEventListener('input',e=>{if(!e.target.classList.contains('order-code'))return;const row=e.target.closest('[data-order-row]'),box=row.querySelector('.order-suggest'),q=e.target.value.trim();if(!q){box.hidden=true;return}const found=search(q).slice(0,5).map(x=>x.product);box.innerHTML=found.map(p=>'<button type="button" data-pick-order-product="'+esc(p.code)+'">'+esc(p.code)+'　'+esc(p.name)+'　<small>'+esc(p.spec)+'</small></button>').join('');box.hidden=!found.length});
document.addEventListener('click',e=>{const b=e.target.closest('[data-pick-order-product]');if(!b)return;const p=findProduct(b.dataset.pickOrderProduct),r=b.closest('[data-order-row]');if(p&&r){r.querySelector('.order-code').value=p.code;r.querySelector('.order-name').value=p.name;r.querySelector('.order-spec').value=p.spec;r.querySelector('.order-suggest').hidden=true}});
function doSearch(){const ticket=++request;$('search-status').textContent='検索中…';clearTimeout(timer);timer=setTimeout(()=>{const started=performance.now();matches=search($('query').value);if(ticket!==request)return;limit=50;renderResults();$('search-status').title=Math.round(performance.now()-started)+'ms';},180);}
$('query').addEventListener('input',()=>{area='';shelf='';setTab('results');doSearch();});$('clear').onclick=()=>{$('query').value='';doSearch();$('query').focus();};$('more').onclick=()=>{limit+=50;renderResults();};
function applyZoom(delta){zoom=Math.max(1,Math.min(2.5,zoom+delta));const drawing=$('drawing'),scroller=$('drawing-scroll');drawing.style.width=(zoom*100)+'%';drawing.style.minWidth=(zoom*100)+'%';if(zoom===1)scroller.scrollTo({left:0,top:0,behavior:'smooth'});}
$('zoom-in').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();applyZoom(.25);});
$('zoom-out').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();applyZoom(-.25);});
$('issue-type').onchange=renderQuality;
$('clear-cache').onclick=async()=>{for(const k of await caches.keys())if(k.startsWith('tanasagashi-'))await caches.delete(k);for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();$('connection').textContent='端末保存を削除済み';};
try{const response=await fetch('data.json',{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);data=await response.json();search=createSearch(data.products);loadOrders();matches=search('');$('loading').hidden=true;$('total').textContent=data.products.length.toLocaleString()+'件 / '+data.locations.filter(l=>l.count).length+'棚';makers=manufacturerIndex(data.products);renderManufacturers();renderPhotos();renderMap();renderQuality();setTab('map');$('connection').textContent=navigator.onLine?'商品データ読込済み':'オフライン';if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=23',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{$('connection').textContent='オンライン利用';});navigator.serviceWorker.addEventListener('message',e=>{if(e.data==='cached')$('connection').textContent='端末に保存済み';});}window.addEventListener('offline',()=>{$('connection').textContent='オフライン';});window.addEventListener('online',()=>{$('connection').textContent='オンライン';});}catch(error){$('loading').innerHTML='データを読み込めませんでした。<br><button id="retry-load">再読み込み</button>';$('connection').textContent='読込エラー';$('retry-load')?.addEventListener('click',()=>window.location.reload());console.error(error);}



function renderManufacturers(){
 const shown=makers.filter(m=>matchManufacturer(m,$('manufacturer-query').value));
 $('manufacturer-count').textContent=shown.length+'件';
 $('manufacturer-list').innerHTML=shown.map(m=>`<button data-manufacturer="${esc(m.name)}"><strong>${esc(m.name)}</strong><span>${m.count.toLocaleString()}商品 →</span></button>`).join('')||'<p class="empty">該当するメーカーがありません。名前の一部でも検索できます。</p>';
}
function selectManufacturer(name){
 clearTimeout(timer);request++;manufacturer=name;area='';shelf='';limit=50;$('query').value='';matches=search('');setTab('results');renderResults();$('results-view').scrollIntoView({behavior:'smooth',block:'start'});
}
$('manufacturer-query').addEventListener('input',renderManufacturers);
$('shelf-photo-input')?.addEventListener('change',e=>scanShelfPhoto(e.target.files?.[0]));
$('shelf-photo-library')?.addEventListener('change',e=>scanShelfPhoto(e.target.files?.[0]));

